### ISSUE TITLE
Complete Wireframe Design

### ISSUE THREAD

**Issue by JackZiyangChen** [agiledev-students-fall2024/4-final-project-marconnect#2]
## Estimation of effort (optional)
- TBD

## Related tasks
- [x] #3

## Acceptance criteria (optional)
- [ ] Must clearly outline the design for every screen in the app
- [ ] Must complete the `UX-DESIGN.md` as outlined in [here](https://github.com/agiledev-students-fall2024/4-final-project-marconnect/blob/master/instructions-0a-app-map-wireframes.md), including all design

**Comment by bloombar** [comment]
Developer is not a user type... so developer needs are not user needs and should not be documented as user stories.  Things that developers need or need to do that are not directly related to a specific user story are `spikes`.

**Comment by JackZiyangChen** [comment]
Task completed during 10/3 meeting
