### ISSUE TITLE
Cleanup and Organize Repository

### ISSUE THREAD

**Issue by JackZiyangChen** [agiledev-students-fall2024/4-final-project-marconnect#4]
## Estimation of effort (optional)

- TBD

## Acceptance criteria (optional)

- [x] Complete `README.md` as outlined in requirement doc
- [x] Complete `CONTRIBUTING.md` as outlined in requirement doc
- [x] Come to a consensus on Team Norm
- [x] Add all `.gitignore`
- [x] Ensure all communication channels are properly set up
- [x] GitHub Board are set up to agile/SCRUM standard

**Comment by brianzou03** [comment]
completed by me [#1 PR: 1:44 pm]
